# Ch03.1 Introducing Series and Index Objects

In [1]:
import numpy as np
import pandas as pd

In [11]:
pd.__version__

'1.5.0'

## The Pandas Series Object

### Constructing Series objects

In [13]:
lst = [0.25, 0.5, 0.75, 1.0]
lst

[0.25, 0.5, 0.75, 1.0]

In [14]:
arr = np.array([0.25, 0.5, 0.75, 1.0])
arr

array([0.25, 0.5 , 0.75, 1.  ])

In [15]:
## 元素資料型態相同
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

``data`` can be a scalar

In [17]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

### ``Series`` as specialized dictionary

In [18]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [19]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [6]:
population['California']

38332521

### ``Series`` as generalized NumPy array

In [20]:
# 字點寫法
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [21]:
# 可以透過index來取內容值
data['b']

0.5

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [10]:
data[5]

0.5

### Series Attributes

In [27]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [31]:
# 這個方法不好
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [30]:
data.to_numpy()

array([0.25, 0.5 , 0.75, 1.  ])

In [32]:
%timeit data.values

350 ns ± 1.03 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [33]:
%timeit data.to_numpy()

705 ns ± 2.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [24]:
data.values?

Type:        property
String form: <property object at 0x7f14653cdc60>
Docstring:  
Return Series as ndarray or ndarray-like depending on the dtype.

.. warning::

   We recommend using :attr:`Series.array` or
   :meth:`Series.to_numpy`, depending on whether you need
   a reference to the underlying data or a NumPy array.

Returns
-------
numpy.ndarray or ndarray-like

See Also
--------
Series.array : Reference to the underlying data.
Series.to_numpy : A NumPy array representing the underlying data.

Examples
--------
>>> pd.Series([1, 2, 3]).values
array([1, 2, 3])

>>> pd.Series(list('aabc')).values
array(['a', 'a', 'b', 'c'], dtype=object)

>>> pd.Series(list('aabc')).astype('category').values
['a', 'a', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']

Timezone aware datetime data is converted to UTC:

>>> pd.Series(pd.date_range('20130101', periods=3,
...                         tz='US/Eastern')).values
array(['2013-01-01T05:00:00.000000000',
       '2013-01-02T05:00:00.000000000

In [34]:
# pandas 特有的資料型態
data.index

RangeIndex(start=0, stop=4, step=1)

In [35]:
data.shape

(4,)

In [36]:
data.ndim

1

In [37]:
# Change Series name
data.name = 'myseries'

In [38]:
data

0    0.25
1    0.50
2    0.75
3    1.00
Name: myseries, dtype: float64

In [17]:
# Change index name
data.index.name = 'myindex'

In [39]:
data

0    0.25
1    0.50
2    0.75
3    1.00
Name: myseries, dtype: float64

In [40]:
# Get data type 
data.dtypes

dtype('float64')

In [42]:
# Return if any NaNs (not a number)
data.hasnans

False

In [43]:
data

0    0.25
1    0.50
2    0.75
3    1.00
Name: myseries, dtype: float64

In [21]:
data[1]

0.5

In [44]:
data[1:3]

1    0.50
2    0.75
Name: myseries, dtype: float64

In [58]:
# index can be duplicated
obj = pd.Series (range(5), index=['a', 'a', 'b', 'b', 'c'])
obj 

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [59]:
# get all objects with index 'a'
obj['a']

a    0
a    1
dtype: int64

In [60]:
# Check if index is unique
obj.index.is_unique

False

## The Pandas Index Object

In [50]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

In [51]:
ind[1]

3

In [52]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [53]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [54]:
ind[1] = 0

TypeError: Index does not support mutable operations